# This file was generated by GoReleaser. DO NOT EDIT.
cask "simplecontainers" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "abe3c1cbd1b80eda24532dea9637353094c59638618a01df06198583dbc58481"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-darwin-amd64"
      binary "simplecontainers-cli-0.1.0-darwin-amd64", target: "simplecontainers"
    end
    on_arm do
      sha256 "8599b63ddf2b4b34564f182c0a9ecf01e8c89fdafbdf7386c6a839de9edb6017"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-darwin-arm64"
      binary "simplecontainers-cli-0.1.0-darwin-arm64", target: "simplecontainers"
    end
  end

  on_linux do
    on_intel do
      sha256 "d6c6685c70a62d41fc225ff4d89ac1150d6f0b512831c38d33dd7c28098dd47c"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-linux-amd64"
      binary "simplecontainers-cli-0.1.0-linux-amd64", target: "simplecontainers"
    end
    on_arm do
      sha256 "2541727fd553943ad380efd4256a6f6eb205663c6de8c8ad97bbba2f1953d20b"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-linux-arm64"
      binary "simplecontainers-cli-0.1.0-linux-arm64", target: "simplecontainers"
    end
  end

  name "simplecontainers"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/simplecontainers", "#{HOMEBREW_PREFIX}/bin/simple"]
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{HOMEBREW_PREFIX}/bin/simplecontainers"]
    end
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/simple"]
  end

  # No zap stanza required

end
