# This file was generated by GoReleaser. DO NOT EDIT.
cask "simplecontainers" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1ae40d9898984ffdf87d146649fab51def112ebb87eabbfd7a4e0053f2b9fa8a"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-darwin-amd64"
      binary "simplecontainers-cli-0.2.0-darwin-amd64", target: "simplecontainers"
    end
    on_arm do
      sha256 "52f4bcbe48c5d6e836e0379c5e87129f24c667cbcdb6d57671855e02d0818c9c"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-darwin-arm64"
      binary "simplecontainers-cli-0.2.0-darwin-arm64", target: "simplecontainers"
    end
  end

  on_linux do
    on_intel do
      sha256 "cdc8cab5025cf29b4435c56f6fb6f9f7304bfc8a11b23df4e0212cc407b53dec"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-linux-amd64"
      binary "simplecontainers-cli-0.2.0-linux-amd64", target: "simplecontainers"
    end
    on_arm do
      sha256 "5c1761ff299e9a7c44f285eec7834ba00ca640d3f6205c91f7a135d0db82d472"
      url "https://files.simplecontainers.app/cli/rel/#{version}/simplecontainers-cli-#{version}-linux-arm64"
      binary "simplecontainers-cli-0.2.0-linux-arm64", target: "simplecontainers"
    end
  end

  name "simplecontainers"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    system_command "/bin/ln", args: ["-sf", "#{HOMEBREW_PREFIX}/bin/simplecontainers", "#{HOMEBREW_PREFIX}/bin/simple"]
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{HOMEBREW_PREFIX}/bin/simplecontainers"]
    end
  end

  uninstall_postflight do
    system_command "/bin/rm", args: ["-f", "#{HOMEBREW_PREFIX}/bin/simple"]
  end

  # No zap stanza required

end
